version: '3'

services:
  ui:
    build: ./todo_frontend
    ports:
      - "8000:80"
  db:
    build: ./todo_database
    ports:
      - "5432:9990"
    environment:
      - POSTGRES_PASSWORD=pwd
  api:
    build: ./todo_backend
    ports: 
      - 9999:9999
